require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe EmailAddressesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # EmailAddress. As you add validations to EmailAddress, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { email: 'asdf', contact_id: 1, contact_type: 'Person'}
  }

  let(:invalid_attributes) {
    { email: nil, contact_id: nil, contact_type: nil}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EmailAddressesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #new" do
    it "assigns a new email_address as @email_address" do
      get :new, {}, valid_session
      expect(assigns(:email_address)).to be_a_new(EmailAddress)
    end
  end

  describe "GET #edit" do
    it "assigns the requested email_address as @email_address" do
      email_address = EmailAddress.create! valid_attributes
      get :edit, {:id => email_address.to_param}, valid_session
      expect(assigns(:email_address)).to eq(email_address)
    end
  end

  describe "POST #create" do
    describe 'with valid params' do
      let(:ingrid) {Person.create(first_name: 'Ingrid', last_name: 'Linda!')}
      let(:valid_attributes) {{ email:'ingrid@gmail.com', contact_id: ingrid.id, contact_type: 'Person'}}


      context "with valid params" do
        it "creates a new EmailAddress" do
          expect {
            post :create, {:email_address => valid_attributes}, valid_session
          }.to change(EmailAddress, :count).by(1)
        end

        it "assigns a newly created email_address as @email_address" do
          post :create, {:email_address => valid_attributes}, valid_session
          expect(assigns(:email_address)).to be_a(EmailAddress)
          expect(assigns(:email_address)).to be_persisted
        end

        it "redirects to the created email_address" do
          post :create, {:email_address => valid_attributes}, valid_session
          expect(response).to redirect_to(ingrid)
        end
      end

      context "with invalid params" do
        it "assigns a newly created but unsaved email_address as @email_address" do
          post :create, {:email_address => invalid_attributes}, valid_session
          expect(assigns(:email_address)).to be_a_new(EmailAddress)
        end

        it "re-renders the 'new' template" do
          post :create, {:email_address => invalid_attributes}, valid_session
          expect(response).to render_template("new")
        end
      end
    end
  end

  describe "PUT #update" do
    describe "with valid params" do 
      let(:bobo) {Person.create(first_name: 'Bob', last_name: 'foobar')}
      let(:valid_attributes) {{ email: 'emaio', contact_id: bobo.id, contact_type: 'Person'}}
      let(:new_attributes) {{ email: 'foobar', contact_id: bobo.id, contact_type: 'Person'}}

      it "updates the requested email_address" do
        email_address = EmailAddress.create! valid_attributes
        put :update, {:id => email_address.to_param, :email_address => new_attributes}, valid_session
        email_address.reload
        expect(email_address.email).to eq('foobar')
        expect(email_address.contact_id).to eq(bobo.id)
      end

      it "assigns the requested email_address as @email_address" do
        email_address = EmailAddress.create! valid_attributes
        put :update, {:id => email_address.to_param, :email_address => valid_attributes}, valid_session
        expect(assigns(:email_address)).to eq(email_address)
      end

      it "redirects to the email_address" do
        email_address = EmailAddress.create! valid_attributes
        put :update, {:id => email_address.to_param, :email_address => valid_attributes}, valid_session
        expect(response).to redirect_to(bobo)
      end
    end

    context "with invalid params" do
      it "assigns the email_address as @email_address" do
        email_address = EmailAddress.create! valid_attributes
        put :update, {:id => email_address.to_param, :email_address => invalid_attributes}, valid_session
        expect(assigns(:email_address)).to eq(email_address)
      end

      it "re-renders the 'edit' template" do
        email_address = EmailAddress.create! valid_attributes
        put :update, {:id => email_address.to_param, :email_address => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    describe 'with valid params' do
      let(:david) { Person.create(first_name: 'David', last_name: 'O')}
      let(:valid_attributes) { {email: 'fdafdsa', contact_id: david.id, contact_type: 'Person'}}

      it "destroys the requested email_address" do
        email_address = EmailAddress.create! valid_attributes
        expect {
          delete :destroy, {:id => email_address.to_param}, valid_session
        }.to change(EmailAddress, :count).by(-1)
      end

      it "redirects to the email_addresses list" do
        email_address = EmailAddress.create! valid_attributes
        delete :destroy, {:id => email_address.to_param}, valid_session
        expect(response).to redirect_to(david)
      end
    end
  end

end
